import type { ToolSource, ToolResult } from '../types';

export const toolSources: ToolSource[] = [
  {
    name: 'Your CRM',
    does: 'Stores deals, contacts, activities',
    cant: "Can't tell you why deals are stalling or which competitor is killing you",
  },
  {
    name: 'Your Call Intelligence',
    does: 'Records calls, scores conversations',
    cant: "Can't connect buyer quotes to CRM outcomes or missing enablement content",
  },
  {
    name: 'Your Knowledge Base',
    does: 'Stores docs, playbooks, battlecards',
    cant: "Can't connect what your reps are hearing on calls to what content should exist but doesn't",
  },
];

export const toolResults: ToolResult[] = [
  {
    icon: '⚔',
    iconBg: 'rgba(245,158,11,0.1)',
    iconColor: 'var(--orange)',
    title: "Find out why you're losing to competitors — and arm your team to win",
    description:
      'RevPlanner reads every lost deal in your CRM, every competitor mention in your call recordings, and every gap in your knowledge base — then builds the battlecard your team is missing. Real buyer quotes. Real differentiation scripts. Win/loss stories from actual deals. One click, distributed to every rep.',
    ticketTag: {
      label: 'COMP ticket',
      colorVar: 'var(--orange)',
      bgRgba: 'rgba(245,158,11,0.08)',
      borderRgba: 'rgba(245,158,11,0.15)',
    },
    actions: '4 actions: Battlecard · Handle Objection · Win/Loss Story · Beat Competitor',
  },
  {
    icon: '💰',
    iconBg: 'rgba(20,184,166,0.1)',
    iconColor: 'var(--teal)',
    title: 'See exactly where your pipeline is leaking — and plug every hole',
    description:
      'RevPlanner cross-references your deal data with call activity to surface the deals that are quietly dying. For each stalled deal, your team gets a recovery plan with a diagnosis of why it stalled, a re-engagement email ready to send, and 3 questions the rep must answer. Their responses feed back into the system, making every future recovery smarter.',
    ticketTag: {
      label: 'PIPE ticket',
      colorVar: 'var(--teal)',
      bgRgba: 'rgba(20,184,166,0.08)',
      borderRgba: 'rgba(20,184,166,0.15)',
    },
    actions: '3 actions: Check Health · At Risk Deals · Check Forecast',
  },
  {
    icon: '🏆',
    iconBg: 'rgba(59,130,246,0.1)',
    iconColor: 'var(--blue)',
    title: "Coach reps with data, not opinions — and prove it's working",
    description:
      "RevPlanner analyzes each rep's calls and deal outcomes, identifies specific skill gaps, and generates a coaching plan with calls to review (with timestamps), a 30/60/90 roadmap, and accountability questions. The rep gets a personalized development plan. The manager gets before/after metrics proving the coaching worked.",
    ticketTag: {
      label: 'COACH ticket',
      colorVar: 'var(--blue)',
      bgRgba: 'rgba(59,130,246,0.08)',
      borderRgba: 'rgba(59,130,246,0.15)',
    },
    actions: '5 actions: Coach This Rep · Show My Performance · Prep My 1:1 · Performance Review · PIP',
  },
  {
    icon: '📑',
    iconBg: 'rgba(102,126,234,0.1)',
    iconColor: 'var(--purple)',
    title: 'Generate the enablement content your team needs — from the data you already have',
    description:
      'Other tools manage content someone else wrote. RevPlanner creates it. Battlecards from your win/loss data. Playbooks from your top performers\' call patterns. Case studies from actual closed deals. Role plays from real objections. Onboarding plans. Certifications. All generated by AI, reviewed by you, published to Confluence in one click.',
    ticketTag: {
      label: 'CONTENT ticket',
      colorVar: 'var(--purple)',
      bgRgba: 'rgba(102,126,234,0.08)',
      borderRgba: 'rgba(102,126,234,0.15)',
    },
    actions: '8 actions: Create Content · Certify Rep · Case Study · Role Play · Onboarding · Playbook · Scale Winner · Training',
  },
];
